oasis4hedev/salsa

app/controllers/admin/periods_controller.rb, app/controllers/documents_controller.rb, app/controllers/organizations_controller.rb, app/controllers/periods_controller.rb, app/controllers/workflow_documents_controller.rb, app/mailers/workflow_mailer.rb, app/models/period.rb, app/views/admin/periods/_form.html.erb, app/views/admin/periods/index.html.erb, app/views/admin/periods/show.html.erb, app/views/components/_edit.html.erb, app/views/organizations/start_workflow_form.html.erb, app/views/periods/_form.html.erb, app/views/periods/index.html.erb, app/views/periods/show.html.erb, db/migrate/20180820162331_remove_cycle_and_sequence_from_periods.rb, db/schema.rb, spec/mailers/previews/workflow_mailer_preview.rb
should be removed from periods
=> should be able to start workflow for period and cycle and sequence

app/assets/javascripts/workflow_document.js, app/controllers/documents_controller.rb, app/controllers/workflow_documents_controller.rb, app/models/document.rb
and supervisors should not be able to approve their own documents
=> supervisors should be able to act like staff 

app/controllers/organizations_controller.rb, app/helpers/application_helper.rb, app/models/document.rb
=> start workflows should start for supervisors and should not start 

app/controllers/admin_controller.rb, app/controllers/application_controller.rb, app/controllers/users/saml_sessions_controller.rb, app/helpers/application_helper.rb, app/models/user.rb
=> username from shibboleth or canvas should be converted to a string 

app/controllers/application_controller.rb, app/views/organization_users/import_users.html.erb, app/views/workflow_documents/_list.html.erb
Import users commit button should say Create Users 
and Organization Admins should be able to create any role besides global admin
=> STAGE: Feedback Create Users and org admin create any role

app/assets/stylesheets/admin.css.scss, app/controllers/admin_controller.rb, app/controllers/admin_users_controller.rb, app/helpers/application_helper.rb, app/models/document.rb, app/views/admin_users/_edit.html.erb, app/views/admin_users/_search_bar.html.erb, app/views/organizations/_show.html.erb, app/views/republish/_preview.html.erb, app/views/workflow_documents/_list.html.erb, public/integrations/canvas/salsaEditButton.js
- fix workflow/documents error
- disable autocomplete on user forms 
- users search should not get archived users 
- change test to be No Documents Found instead of no SALSAs found 
- org admins should be able to edit orgs accross domains
=> STAGE: bug fixes

app/assets/stylesheets/admin.css.scss, app/controllers/admin_controller.rb, app/controllers/application_controller.rb, app/controllers/organizations_controller.rb, app/models/document.rb, app/models/user.rb, app/views/admin/_topbar.html.erb, app/views/admin/request_access.html.erb, app/views/admin/unassigned_user.html.erb, app/views/instances/default/_new_unassigned_user_email.liquid, app/views/instances/default/_request_access_success.html.erb, app/views/instances/default/_unassigned_user.html.erb, app/views/layouts/_sidebar.html.erb, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb, app/views/layouts/workflow.html.erb, app/views/organization_users/import_users.html.erb, app/views/organizations/index.html.erb, app/views/organizations/orphaned_documents.html.erb, config/routes.rb
(request access before sending the message)
=> STAGE: change inactive notification to require the user to click a button 

app/controllers/admin_controller.rb, app/controllers/admin_documents_base_controller.rb, app/controllers/admin_documents_controller.rb, app/controllers/application_controller.rb, app/controllers/components_controller.rb, app/controllers/organizations_controller.rb, app/controllers/workflow_documents_controller.rb, app/helpers/application_helper.rb, app/models/document.rb, app/models/organization.rb, app/views/organizations/_show.html.erb, app/views/workflow_documents/_list.html.erb
and fixed some other bugs around workflow/admin documents
=> added admin_documents_base_controller

app/assets/javascripts/script.js, app/controllers/workflow_steps_controller.rb, app/helpers/application_helper.rb, app/views/admin_users/show.html.erb, app/views/assignments/_org_list.html.haml
fix manage users button && add link to manage users page
=> order workflow steps newest first && fix salsa partial stack level to deep error &&

app/assets/javascripts/script.js, app/controllers/workflow_documents_controller.rb, app/controllers/workflow_steps_controller.rb, app/helpers/application_helper.rb, app/views/admin_users/show.html.erb, app/views/assignments/_org_list.html.haml
- order workflow steps newest first &&
- fix salsa partial stack level to deep error &&
- fix manage users button &&
- add link to manage users page
=> ready for master: bug fixes

app/controllers/workflow_steps_controller.rb, app/helpers/application_helper.rb, app/models/document.rb, app/views/admin_users/show.html.erb, app/views/assignments/_org_list.html.haml
- order workflow steps newest first &&
- fix salsa partial stack level to deep error &&
- fix manage users button &&
- add link to manage users page
=> Master: bug fixes

app/controllers/admin_users_controller.rb
app/controllers/admin_users_controller.rb
=> check if user_ids exist before using the variable

app/assets/stylesheets/admin.css.scss, app/assets/stylesheets/application.css, app/assets/stylesheets/pagination.css.scss, app/helpers/application_helper.rb, app/models/organization.rb, app/views/admin/search.html.erb, app/views/workflow_documents/_list.html.erb
add pagination to workflow documents
=> stage: improve efficiency of has_role and find_org_by_path and 

app/views/admin_documents/edit.html.erb
make documents user_id editable
=> make documents user_id editable

app/controllers/admin_documents_controller.rb
on the document properties editor @organization was nil.
=> hotfix/ fixed the the document properties editor issue

app/controllers/admin_controller.rb, app/controllers/documents_controller.rb, app/models/document.rb, app/views/documents/_relink.html.haml, app/views/documents/course_select.html.haml
3 issues fixed.
1. now it shows the course select dialog if there is no document with the course.
2. if a someone was authenticated through canvas it no longer fails when it dose not find their user.
3. after correcting olny to only some admin pages complained about the organization being nil. that is now fixed.
=> hotfix / select course dialog issues

app/controllers/documents_controller.rb, app/views/documents/_relink.html.haml, app/views/documents/course_select.html.haml
If it cant find an existing document by the lms_course_id then look for one by the document token.
=> bugfix / find existing document by the document token

app/controllers/admin/auditor_controller.rb, app/helpers/application_helper.rb, features/step_definitions/steps.rb, spec/helpers/application_helper_spec.rb
added unit tests for the find_org_by_path helper and refactored it using a suggestion from @capnregex
=> Bugfix  / improve  find_org_by_path

app/models/organization.rb
This passes the organization#setting and organization#root_org_setting unit tests.
=> memoized the organization setting methods

app/controllers/documents_controller.rb
changed the check from setting to root org setting
=> bugfix/changed redirect_by_lms_account_id check to root_org_setting.

app/views/documents/content.html.erb, app/views/instances/default/_content_footer.html.erb, app/views/instances/default/_content_header.html.erb
built for adding something like a print link right before the document content.
=> added content_header and content_footer components

app/views/documents/content.html.erb, app/views/instances/default/_content_footer.html.erb, app/views/instances/default/_content_header.html.erb
=> Revert "added content_header and content_footer components"
